In [18]:
import torch

#exercise 1
tensors_list =[]

one_dim = torch.tensor([1,2,3,4,5])
tensors_list.append(one_dim)
two_by_three = torch.zeros(size=[2,3])
tensors_list.append(two_by_three)
three_by_three = torch.rand(size=[3,3])
tensors_list.append(three_by_three)
zero_to_ten = torch.arange(start=0, end=11, step=2)
tensors_list.append(zero_to_ten)

for t in tensors_list:
    print(f"{t}\n→ shape: {t.shape}, dtype: {t.dtype}, device: {t.device}\n")

tensor([1, 2, 3, 4, 5])
→ shape: torch.Size([5]), dtype: torch.int64, device: cpu

tensor([[0., 0., 0.],
        [0., 0., 0.]])
→ shape: torch.Size([2, 3]), dtype: torch.float32, device: cpu

tensor([[0.7583, 0.5937, 0.9625],
        [0.5167, 0.0379, 0.8898],
        [0.1243, 0.0361, 0.6056]])
→ shape: torch.Size([3, 3]), dtype: torch.float32, device: cpu

tensor([ 0,  2,  4,  6,  8, 10])
→ shape: torch.Size([6]), dtype: torch.int64, device: cpu



In [26]:
#exercise 2
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"A + B = {A + B}")
print(f"A - B = {A - B}")
print(f"A @ B = {torch.matmul(A, B)}")
print(f"Mean of A = {A.mean()}")
print(f"Std of A = {A.std()}")

C = torch.tensor([10, 20])
print(f"A + C = {A + C}")

A + B = tensor([[ 6.,  8.],
        [10., 12.]])
A - B = tensor([[-4., -4.],
        [-4., -4.]])
A @ B = tensor([[19., 22.],
        [43., 50.]])
Mean of A = 2.5
Std of A = 1.29099440574646
A + C = tensor([[11., 22.],
        [13., 24.]])


In [62]:
#exercise 3 (indexing and slicing)
X = torch.arange(1, 17).reshape(4, 4)
print(f"Second row: {X[1]}")
print(f"Second third column: {X.select(1, 2)}") #or simply X[:,2]
reshaped = X.reshape(8,2)
sub_mat = torch.cat((reshaped[0],reshaped[2]), 0).reshape(2,2) #X[:2, :2]
print(f"top-left 2×2 submatrix: {sub_mat}")

#Replace the last row with zeros.
X[-1] = torch.zeros_like(X[-1])

#Reverse the order of rows.
reversed_X = torch.flip(X, [0])
reversed_X

Second row: tensor([5, 6, 7, 8])
Second third column: tensor([ 3,  7, 11, 15])
top-left 2×2 submatrix: tensor([[1, 2],
        [5, 6]])


tensor([[ 0,  0,  0,  0],
        [ 9, 10, 11, 12],
        [ 5,  6,  7,  8],
        [ 1,  2,  3,  4]])

In [85]:
#exercise 4 — Tensor Reshaping and Stacking
#1.Create a tensor of shape (2, 3, 4) filled with random numbers.
T = torch.rand(size=(2,3,4))

#Reshape it into (3, 8) and (4, 6) — verify total elements are consistent.
reshaped_T1 = T.reshape(3,8)
print(f"(3, 8) shape: {reshaped_T1}")
reshaped_T2 = T.reshape(4,6)
print(f"(4, 6) shape: {reshaped_T2}")

#Split the tensor into two equal parts along the second dimension.
reshaped_T3 = T.reshape(2,4,3)
print(reshaped_T3)
first_slice = reshaped_T3[:,:2,:].reshape(2,3,2)
print(first_slice)
second_slice = reshaped_T3[:,2:,:].reshape(2,3,2)
second_slice

sliced = torch.tensor_split(T, 2, dim=1)
sliced

#Stack two 1D tensors [1,2,3] and [4,5,6]:
T1 = torch.tensor([1,2,3])
T2 = torch.tensor([4,5,6])
#Vertically → shape (2, 3)
torch.stack((T1,T2), dim=0)
#Horizontally → shape (3, 2) using torch.stack and torch.cat.
torch.stack((T1,T2), dim=1)

(3, 8) shape: tensor([[0.6399, 0.1093, 0.0674, 0.2513, 0.4417, 0.4643, 0.6666, 0.3322],
        [0.4385, 0.5259, 0.7648, 0.9321, 0.9795, 0.4720, 0.7766, 0.5725],
        [0.0282, 0.5654, 0.1333, 0.6035, 0.3754, 0.2219, 0.9395, 0.2132]])
(4, 6) shape: tensor([[0.6399, 0.1093, 0.0674, 0.2513, 0.4417, 0.4643],
        [0.6666, 0.3322, 0.4385, 0.5259, 0.7648, 0.9321],
        [0.9795, 0.4720, 0.7766, 0.5725, 0.0282, 0.5654],
        [0.1333, 0.6035, 0.3754, 0.2219, 0.9395, 0.2132]])
tensor([[[0.6399, 0.1093, 0.0674],
         [0.2513, 0.4417, 0.4643],
         [0.6666, 0.3322, 0.4385],
         [0.5259, 0.7648, 0.9321]],

        [[0.9795, 0.4720, 0.7766],
         [0.5725, 0.0282, 0.5654],
         [0.1333, 0.6035, 0.3754],
         [0.2219, 0.9395, 0.2132]]])
tensor([[[0.6399, 0.1093],
         [0.0674, 0.2513],
         [0.4417, 0.4643]],

        [[0.9795, 0.4720],
         [0.7766, 0.5725],
         [0.0282, 0.5654]]])


tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [86]:
T

tensor([[[0.6399, 0.1093, 0.0674, 0.2513],
         [0.4417, 0.4643, 0.6666, 0.3322],
         [0.4385, 0.5259, 0.7648, 0.9321]],

        [[0.9795, 0.4720, 0.7766, 0.5725],
         [0.0282, 0.5654, 0.1333, 0.6035],
         [0.3754, 0.2219, 0.9395, 0.2132]]])